version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    image: sieun96/tripnow:latest
    ports:
      - "8080:8080"
    environment:
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_MAIL_PASSWORD: "${GOOGLE_MAIL_PASSWORD}"
      GOOGLE_MAIL_USERNAME: "${GOOGLE_MAIL_USERNAME}"
      GOOGLE_REDIRECT_URL: "${GOOGLE_REDIRECT_URL}"
      SECRET_KEY: "${SECRET_KEY}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql-data:
  redis-data:
